buildDraft = false
allowUnsafeHTML = true
cleanBuild = true
baseTemplatePath = "base.tmpl"

[rss]
generate = true
title = "Patrick Dewey"
description = ""
url = "pdewey.com"

[[routes]]
contentPath = "index.md"
outputPattern = "/" 
template = "_index.tmpl"

[[routes]]
contentPath = "writing.md"
outputPattern = "/writing/"
template = "writing.tmpl"

[[routes]]
contentPath = "writing"
outputPattern = "/writing/:slug"
template = "post.tmpl"
generateRSS = true

[[routes]]
contentPath = "projects.md"
outputPattern = "/projects/"
template = "projects.tmpl"
