buildDraft = false
allowUnsafeHTML = true
cleanBuild = true

[rss]
generate = true
title = "Patrick Dewey"
description = ""
url = "pdewey.com"

[[routes]]
contentPath = "index.md"
outputPattern = "/" 
template = "_index.html"

[[routes]]
contentPath = "writing.md"
outputPattern = "/writing/"
template = "writing.html"

[[routes]]
contentPath = "writing"
outputPattern = "/writing/:slug"
template = "post.html"
generateRSS = true

[[routes]]
contentPath = "projects.md"
outputPattern = "/projects/"
template = "projects.html"
